server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  application:
   name: CafeInfo-Service 
    
## name of the client (or) SpringBoot App
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
     
## it create an instance on eureka server 

  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
      ## it the eureka server
  
pivotal:
  cafeinfoservice:
    name: CafeInfo-Service
  cafereviewservice:
    name: CafeReview-Service    
    ## name of microservices 
